import type { Metadata } from "next";
import "./styles/base/reset/reset.scss";
import Menu from "./components/menu";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
